/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Question = IDL.Record({
  'id' : IDL.Nat,
  'difficulty' : IDL.Nat,
  'text' : IDL.Text,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const GameSession = IDL.Record({
  'mode' : IDL.Text,
  'timestamp' : Time,
  'truthScore' : IDL.Nat,
  'sessionId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getQuestionById' : IDL.Func([IDL.Nat], [Question], ['query']),
  'getQuestions' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'getTopScores' : IDL.Func([], [IDL.Vec(GameSession)], ['query']),
  'saveSession' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'difficulty' : IDL.Nat,
    'text' : IDL.Text,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const GameSession = IDL.Record({
    'mode' : IDL.Text,
    'timestamp' : Time,
    'truthScore' : IDL.Nat,
    'sessionId' : IDL.Nat,
  });
  
  return IDL.Service({
    'getQuestionById' : IDL.Func([IDL.Nat], [Question], ['query']),
    'getQuestions' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
    'getTopScores' : IDL.Func([], [IDL.Vec(GameSession)], ['query']),
    'saveSession' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };